name: "Create Language Translation PR"
description: "Create a translation PR for scientific python project"
author: "@goanpeca"
inputs:
  source-repo:
    description: "Source repository"
    required: true
  gpg_private_key:
    description: "GPG private key of the user/email making the commits"
    required: true
  passphrase: 
    description: "GPG passphrase of the user/email making the commits"
    required: true    
  token:
    description: "Github personal access token of the account performing the github operations"
    required: true
  crowdin-token:
    description: "Crowdin personal access token of the account performing the github operations"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: 'Scientific-Python-Translations/translations-sync'
    - name: Import GPG key
      id: import-gpg
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ inputs.GPG_PRIVATE_KEY }}
        passphrase: ${{ inputs.PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true
        git_config_global: true
    - name: Configure commit signing
      shell: bash
      run: |
          git config --global user.name "${{ steps.import-gpg.outputs.name }}"
          git config --global user.email "${{ steps.import-gpg.outputs.email }}"
    - name: Configure python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' # '3.x'
    - name: Run scripts
      shell: bash
      env:
        TOKEN: ${{ inputs.TOKEN }}
        CROWDIN_TOKEN: ${{ inputs.CROWDIN-TOKEN }}
        INPUT_SOURCE-REPO: ${{ inputs.SOURCE-REPO }}
        INPUT_SOURCE-FOLDER: ${{ inputs.SOURCE-FOLDER }}
        INPUT_SOURCE-REF: ${{ inputs.SOURCE-REF }}
        INPUT_TRANSLATIONS-REPO: ${{ inputs.TRANSLATIONS-REPO }}
        INPUT_TRANSLATIONS-FOLDER: ${{ inputs.TRANSLATIONS-FOLDER }}
        INPUT_TRANSLATIONS-REF: ${{ inputs.TRANSLATIONS-REF }}
        GPG_NAME: ${{ steps.import-gpg.outputs.name }}
        GPG_EMAIL: ${{ steps.import-gpg.outputs.email }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install crowdin-api-client pygithub requests
        python main.py
