# maps language codes to language name used in Crowdin.
# https://developer.crowdin.com/language-codes/
language_code_map = {
    'ach': 'Acholi',
    'aa': 'Afar',
    'af': 'Afrikaans',
    'ak': 'Akan',
    'tw': 'Akan, Twi',
    'sq': 'Albanian',
    'am': 'Amharic',
    'ar': 'Arabic',
    'ar-bh': 'Arabic, Bahrain',
    'ar-eg': 'Arabic, Egypt',
    'ar-sa': 'Arabic, Saudi Arabia',
    'ar-ye': 'Arabic, Yemen',
    'an': 'Aragonese',
    'hy': 'Armenian',
    'frp': 'Arpitan',
    'as': 'Assamese',
    'ast': 'Asturian',
    'tay': 'Atayal',
    'av': 'Avaric',
    'ae': 'Avestan',
    'ay': 'Aymara',
    'az': 'Azerbaijani',
    'ban': 'Balinese',
    'bal': 'Balochi',
    'bm': 'Bambara',
    'ba': 'Bashkir',
    'eu': 'Basque',
    'be': 'Belarusian',
    'bn': 'Bengali',
    'bn-in': 'Bengali, India',
    'ber': 'Berber',
    'bh': 'Bihari',
    'bfo': 'Birifor',
    'bi': 'Bislama',
    'bs': 'Bosnian',
    'br': 'Breton',
    'bg': 'Bulgarian',
    'my': 'Burmese',
    'ca': 'Catalan',
    'ceb': 'Cebuano',
    'ch': 'Chamorro',
    'ce': 'Chechen',
    'chr': 'Cherokee',
    'ny': 'Chewa',
    'zh-cn': 'Chinese Simplified',
    'zh-tw': 'Chinese Traditional',
    'zh-hk': 'Chinese Traditional, Hong Kong',
    'zh-mo': 'Chinese Traditional, Macau',
    'zh-sg': 'Chinese Traditional, Singapore',
    'cv': 'Chuvash',
    'kw': 'Cornish',
    'co': 'Corsican',
    'cr': 'Cree',
    'hr': 'Croatian',
    'cs': 'Czech',
    'da': 'Danish',
    'fa-af': 'Dari',
    'dv': 'Dhivehi',
    'nl': 'Dutch',
    'nl-be': 'Dutch, Belgium',
    'nl-sr': 'Dutch, Suriname',
    'dz': 'Dzongkha',
    'en': 'English',
    'en-ar': 'English, Arabia',
    'en-au': 'English, Australia',
    'en-bz': 'English, Belize',
    'en-ca': 'English, Canada',
    'en-cb': 'English, Caribbean',
    'en-cn': 'English, China',
    'en-dk': 'English, Denmark',
    'en-hk': 'English, Hong Kong',
    'en-in': 'English, India',
    'en-id': 'English, Indonesia',
    'en-ie': 'English, Ireland',
    'en-jm': 'English, Jamaica',
    'en-ja': 'English, Japan',
    'en-my': 'English, Malaysia',
    'en-nz': 'English, New Zealand',
    'en-no': 'English, Norway',
    'en-ph': 'English, Philippines',
    'en-pr': 'English, Puerto Rico',
    'en-sg': 'English, Singapore',
    'en-za': 'English, South Africa',
    'en-se': 'English, Sweden',
    'en-gb': 'English, United Kingdom',
    'en-us': 'English, United States',
    'en-zw': 'English, Zimbabwe',
    'eo': 'Esperanto',
    'et': 'Estonian',
    'ee': 'Ewe',
    'fo': 'Faroese',
    'fj': 'Fijian',
    'fil': 'Filipino',
    'fi': 'Finnish',
    'vls': 'Flemish',
    'fra': 'Franconian',
    'fr': 'French',
    'fr-be': 'French, Belgium',
    'fr-ca': 'French, Canada',
    'fr-lu': 'French, Luxembourg',
    'fr-qc': 'French, Quebec',
    'fr-ch': 'French, Switzerland',
    'fy': 'Frisian',
    'fur': 'Friulian',
    'ff': 'Fula',
    'gaa': 'Ga',
    'gl': 'Galician',
    'ka': 'Georgian',
    'de': 'German',
    'de-at': 'German, Austria',
    'de-be': 'German, Belgium',
    'de-li': 'German, Liechtenstein',
    'de-lu': 'German, Luxembourg',
    'de-ch': 'German, Switzerland',
    'el': 'Greek',
    'el-cy': 'Greek, Cyprus',
    'kl': 'Greenlandic',
    'gn': 'Guarani',
    'gu': 'Gujarati',
    'ht': 'Haitian Creole',
    'ha': 'Hausa',
    'haw': 'Hawaiian',
    'he': 'Hebrew',
    'hz': 'Herero',
    'hil': 'Hiligaynon',
    'hi': 'Hindi',
    'ho': 'Hiri Motu',
    'hmn': 'Hmong',
    'hu': 'Hungarian',
    'is': 'Icelandic',
    'ido': 'Ido',
    'ig': 'Igbo',
    'ilo': 'Ilokano',
    'id': 'Indonesian',
    'iu': 'Inuktitut',
    'ga': 'Irish',
    'it': 'Italian',
    'it-ch': 'Italian, Switzerland',
    'ja': 'Japanese',
    'jv': 'Javanese',
    'quc': "K'iche'",
    'kab': 'Kabyle',
    'kn': 'Kannada',
    'pam': 'Kapampangan',
    'ks': 'Kashmiri',
    'ks-pk': 'Kashmiri, Pakistan',
    'csb': 'Kashubian',
    'kk': 'Kazakh',
    'km': 'Khmer',
    'rw': 'Kinyarwanda',
    'kv': 'Komi',
    'kg': 'Kongo',
    'kok': 'Konkani',
    'ko': 'Korean',
    'ku': 'Kurdish',
    'kmr': 'Kurmanji (Kurdish)',
    'kj': 'Kwanyama',
    'ky': 'Kyrgyz',
    'lo': 'Lao',
    'la': 'Latin',
    'lv': 'Latvian',
    'lij': 'Ligurian',
    'li': 'Limburgish',
    'ln': 'Lingala',
    'lt': 'Lithuanian',
    'nds': 'Low German',
    'dsb': 'Lower Sorbian',
    'lg': 'Luganda',
    'luy': 'Luhya',
    'lb': 'Luxembourgish',
    'mk': 'Macedonian',
    'mai': 'Maithili',
    'mg': 'Malagasy',
    'ms': 'Malay',
    'ms-bn': 'Malay, Brunei',
    'ml': 'Malayalam',
    'mt': 'Maltese',
    'mi': 'Maori',
    'arn': 'Mapudungun',
    'mr': 'Marathi',
    'mh': 'Marshallese',
    'mn': 'Mongolian',
    'mos': 'Mossi',
    'na': 'Nauru',
    'ng': 'Ndonga',
    'ne': 'Nepali',
    'ne-in': 'Nepali, India',
    'pcm': 'Nigerian Pidgin',
    'se': 'Northern Sami',
    'nso': 'Northern Sotho',
    'no': 'Norwegian',
    'nb': 'Norwegian Bokmal',
    'nn-no': 'Norwegian Nynorsk',
    'oc': 'Occitan',
    'or': 'Odia',
    'oj': 'Ojibwe',
    'om': 'Oromo',
    'os': 'Ossetian',
    'pi': 'Pali',
    'pap': 'Papiamento',
    'ps': 'Pashto',
    'fa': 'Persian',
    'pl': 'Polish',
    'pt': 'Portuguese',
    'pt-br': 'Portuguese, Brazilian',
    'pa': 'Punjabi',
    'pa-pk': 'Punjabi, Pakistan',
    'qu': 'Quechua',
    'ro': 'Romanian',
    'rm': 'Romansh',
    'rn': 'Rundi',
    'ru': 'Russian',
    'ru-by': 'Russian, Belarus',
    'ru-md': 'Russian, Moldova',
    'sah': 'Sakha',
    'sg': 'Sango',
    'sa': 'Sanskrit',
    'sat': 'Santali',
    'sc': 'Sardinian',
    'sco': 'Scots',
    'gd': 'Scottish Gaelic',
    'sr': 'Serbian',
    'sr-cyrl': 'Serbian (Cyrillic)',
    'sr-latn': 'Serbian (Latin)',
    'sh': 'Serbo-Croatian',
    'crs': 'Seychellois Creole',
    'sn': 'Shona',
    'ii': 'Sichuan Yi',
    'sd': 'Sindhi',
    'si': 'Sinhala',
    'sk': 'Slovak',
    'sl': 'Slovenian',
    'so': 'Somali',
    'son': 'Songhay',
    'ckb': 'Sorani (Kurdish)',
    'nr': 'Southern Ndebele',
    'sma': 'Southern Sami',
    'st': 'Southern Sotho',
    'es': 'Spanish',
    'es-em': 'Spanish (Modern)',
    'es-ar': 'Spanish, Argentina',
    'es-bo': 'Spanish, Bolivia',
    'es-cl': 'Spanish, Chile',
    'es-co': 'Spanish, Colombia',
    'es-cr': 'Spanish, Costa Rica',
    'es-do': 'Spanish, Dominican Republic',
    'es-ec': 'Spanish, Ecuador',
    'es-sv': 'Spanish, El Salvador',
    'es-gt': 'Spanish, Guatemala',
    'es-hn': 'Spanish, Honduras',
    'es-419': 'Spanish, Latin America',
    'es-mx': 'Spanish, Mexico',
    'es-ni': 'Spanish, Nicaragua',
    'es-pa': 'Spanish, Panama',
    'es-py': 'Spanish, Paraguay',
    'es-pe': 'Spanish, Peru',
    'es-pr': 'Spanish, Puerto Rico',
    'es-us': 'Spanish, United States',
    'es-uy': 'Spanish, Uruguay',
    'es-ve': 'Spanish, Venezuela',
    'su': 'Sundanese',
    'sw': 'Swahili',
    'sw-ke': 'Swahili, Kenya',
    'sw-tz': 'Swahili, Tanzania',
    'ss': 'Swati',
    'sv': 'Swedish',
    'sv-fi': 'Swedish, Finland',
    'syc': 'Syriac',
    'tl': 'Tagalog',
    'ty': 'Tahitian',
    'tg': 'Tajik',
    'ta': 'Tamil',
    'tt': 'Tatar',
    'te': 'Telugu',
    'kdh': 'Tem (Kotokoli)',
    'th': 'Thai',
    'bo': 'Tibetan',
    'ti': 'Tigrinya',
    'ts': 'Tsonga',
    'tn': 'Tswana',
    'tr': 'Turkish',
    'tr-cy': 'Turkish, Cyprus',
    'tk': 'Turkmen',
    'uk': 'Ukrainian',
    'hsb': 'Upper Sorbian',
    'ur-in': 'Urdu (India)',
    'ur': 'Urdu (Pakistan)',
    'ug': 'Uyghur',
    'uz': 'Uzbek',
    'val': 'Valencian',
    've': 'Venda',
    'vec': 'Venetian',
    'vi': 'Vietnamese',
    'wa': 'Walloon',
    'cy': 'Welsh',
    'wo': 'Wolof',
    'xh': 'Xhosa',
    'yi': 'Yiddish',
    'yo': 'Yoruba',
    'zea': 'Zeelandic',
    'zu': 'Zulu'
}

    
def filter_commits(filename: str, language_code: str) -> None:
    """Edits the git-rebase-todo file to pick only commits for one language

    Used in GIT_SEQUENCE_EDITOR for scripted interactive rebase.

    Parameters
    ----------
    filename : str
    language_code : str
        Crowdin language code.
    """
    language = language_code_map[language_code.lower()]

    with open(filename) as f:
        lines = [line.strip().split(maxsplit=2) for line in f.readlines()]
    lines = [
        line for line in lines
        if line and line[0] == "pick" and language in line[-1]
    ]
    output = '\n'.join(' '.join(line) for line in lines) + '\n'
    with open(filename, 'w') as f:
        f.write(output)
